#!/usr/bin/env python3
"""Write src/s57/codes.rs, the S-57 object class and attribute tables.

The tables are the IHO S-57 edition 3.1 object catalogue, as GDAL ships it
(ogr/ogrsf_frmts/s57/data, MIT licensed). Fetch the two CSVs from there:

    python3 scripts/gen-codes.py s57objectclasses.csv s57attributes.csv
"""
import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
objects, attributes = sys.argv[1], sys.argv[2]


def rust(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


out = [
    "// Generated by scripts/gen-codes.py from the S-57 object catalogue. Do not edit.",
    "",
    "/// (code, acronym, name) for every S-57 object class.",
    "pub const OBJECT_CLASSES: &[(u16, &str, &str)] = &[",
]
for r in csv.DictReader(open(objects, encoding="latin-1")):
    out.append(f"    ({int(r['Code'])}, {rust(r['Acronym'])}, {rust(r['ObjectClass'].strip())}),")
out += [
    "];",
    "",
    "/// (code, acronym, name, type) for every S-57 attribute. The type is E",
    "/// (enumerated), L (list), F (float), I (integer), A (coded string) or S",
    "/// (free text).",
    "pub const ATTRIBUTES: &[(u16, &str, &str, u8)] = &[",
]
for r in csv.DictReader(open(attributes, encoding="latin-1")):
    t = r["Attributetype"].strip() or "S"
    # A few rows are placeholders with no acronym or type.
    if t not in "ELFIAS" or len(t) != 1 or r["Acronym"] == "N/A":
        continue
    out.append(f"    ({int(r['Code'])}, {rust(r['Acronym'])}, {rust(r['Attribute'].strip())}, b'{t}'),")
out += ["];", ""]
(ROOT / "src/s57/codes.rs").write_text("\n".join(out))
